"""On-page SEO copy for the build: title tags, meta descriptions, keyword-bearing H2 rewrites and local notes.

Titles stay at 60 characters or fewer including the short brand suffix. Descriptions aim for 120 to 155 characters.
Edit this file and run `python3 build.py` to update the whole site.
"""

BRAND = " | Extera"

SEO = {
    "index": ("Business Telecoms and Phone Systems in Banbury",
              "Extera supplies business phone systems, broadband, leased lines, mobiles and data cabling across the UK from Banbury. Get a free quote."),
    "phone-systems": ("Business Phone Systems UK: 3CX, 8x8, Gamma, Avaya",
                      "Compare cloud, hosted and on-premise business phone systems: 3CX, 8x8, Gamma Horizon and Avaya IP Office, supplied and supported by Extera."),
    "3cx": ("3CX Phone System Supplier UK, Gold Partner",
            "Buy, install and support a 3CX phone system from a UK 3CX Gold Partner. Hosted or onsite, with pricing advice and a free trial. Get a quote."),
    "3cx-apps": ("3CX Mobile, Desktop and Web Apps (Softphone)",
                 "The 3CX app for iPhone, Android, Windows and browser: take business calls, chat and meetings anywhere. Ask Extera to set it up for your team."),
    "3cx-video-chat": ("3CX Video Conferencing, Live Chat and WhatsApp",
                       "3CX video meetings for up to 250 people, website live chat, WhatsApp and SMS, all included. Talk to a 3CX Gold Partner about your set-up."),
    "3cx-integrations": ("3CX CRM and Microsoft 365 Integration",
                         "Connect 3CX to Salesforce, HubSpot, Microsoft 365 and Teams, with Call Flow Designer for custom call handling. Ask Extera to plan it."),
    "3cx-ai-analytics": ("3CX Call Centre Features, Reporting and AI",
                         "3CX call centre tools: queues, wallboard, recording, reporting, transcription and AI call summaries, included with your phone system."),
    "3cx-vs-8x8": ("3CX vs 8x8: Cost, Features and Reviews Compared",
                   "3CX or 8x8? A plain-English UK comparison of cost, contact centre, support and G2 review scores. Get a side-by-side quote from Extera."),
    "8x8": ("8x8 Phone System UK: Reseller and Partner",
            "Extera supplies, sets up and supports 8x8 cloud phone systems for UK businesses: calls, meetings and contact centre on one platform. Get a quote."),
    "8x8-voice": ("8x8 Business Phone, Voicemail and Team Chat",
                  "8x8 cloud phone system features: auto attendant, voicemail transcription, call recording and team chat on desktop and mobile. Ask Extera for advice."),
    "8x8-meetings": ("8x8 Video Conferencing and Meetings",
                     "8x8 video conferencing guests join from a browser, with screen sharing, recording and calendar links. Ask Extera to plan the rooms and network."),
    "8x8-contact-centre": ("8x8 Contact Centre Features and Functionality",
                           "8x8 cloud contact centre: omnichannel routing, IVR, dialler, quality and workforce management, analytics and AI. Get a contact centre quote."),
    "8x8-integrations": ("8x8 Microsoft Teams, Salesforce and CRM Links",
                         "8x8 integrates with Microsoft Teams, Salesforce, Dynamics, Zendesk and NetSuite, with open APIs. Ask Extera how it fits your tools."),
    "8x8-security": ("8x8 Security, 99.999% Uptime and Compliance",
                     "8x8 security and reliability: a 99.999% uptime SLA, multi-factor authentication, ISO 27001 and data residency questions answered by Extera."),
    "gamma-horizon": ("Gamma Horizon Phone System, Hosted Telephony",
                      "Gamma Horizon hosted phone system on Gamma's UK network, with Teams, Webex, contact centre and analytics. Supplied and supported by Extera."),
    "gamma-horizon-apps": ("Gamma Horizon Collaborate and Mobile App",
                           "Horizon Collaborate and the Horizon mobile app: chat, calls and video on desktop, phone and browser. Ask Extera about Gamma Horizon."),
    "gamma-horizon-teams": ("Gamma Horizon for Teams: Direct Routing and Webex",
                            "Horizon for Teams adds Gamma calling to Microsoft Teams via direct routing, or choose Horizon with Webex. Get advice from Extera."),
    "gamma-horizon-contact": ("Gamma Horizon Contact Centre (Horizon Contact)",
                              "Horizon Contact is a cloud contact centre for Gamma Horizon: queues, callback, IVR and CRM integration. Get a quote from Extera."),
    "gamma-horizon-analytics": ("Akixi Call Analytics and CRM for Gamma Horizon",
                                "Akixi call analytics, wallboards, a receptionist console and links to 200+ CRM packages for Gamma Horizon. Ask Extera for a demo."),
    "gamma-horizon-network": ("Gamma Horizon Network, Failover and Support",
                              "Gamma Horizon runs on Gamma's UK network with data-centre failover, call diversion and 24/7 first-line support. Ask Extera."),
    "avaya-ip-office": ("Avaya IP Office Partner UK: Supply and Support",
                        "Extera, an Avaya Silver Partner, supplies, upgrades and supports Avaya IP Office phone systems, onsite or by subscription. Get a quote."),
    "avaya-ipo-editions": ("Avaya IP Office Editions, Select and Subscription",
                           "Avaya IP Office editions explained: Basic, Essential, Preferred, Server Edition, Select and Subscription. Ask Extera which one fits."),
    "avaya-ipo-apps": ("Avaya Workplace, one-X Portal and DECT Phones",
                       "Avaya Workplace, one-X Portal, DECT handsets and home working for Avaya IP Office. Ask Extera to plan your set-up and handsets."),
    "avaya-ipo-contact-centre": ("Avaya IP Office Contact Centre and Call Reporting",
                                 "Add call reporting, recording or a multichannel contact centre to Avaya IP Office. Extera, an Avaya partner, can quote and install."),
    "avaya-ipo-resilience": ("Avaya IP Office R12 Upgrade, Support and Resilience",
                             "Keep Avaya IP Office supported: R12 upgrade path, survivability, SIP and security, with maintenance from Extera. Check your release."),
    "contact-centres": ("Contact Centre Software and Solutions UK",
                        "Contact centre software for UK teams: queues, IVR, recording and CRM integration on 3CX, 8x8, Gamma and Avaya. Get a quote from Extera."),
    "connectivity": ("Business Connectivity: Broadband, Leased Lines",
                     "Business broadband, leased lines, MPLS, SIP trunks and 4G backup matched to your sites. Extera compares UK carriers for you. Get a quote."),
    "fibre-broadband": ("Business Fibre Broadband: FTTP, FTTC and SOGEA",
                        "Compare business fibre broadband: FTTP, FTTC and SOGEA with static IPs and support. Send Extera your postcode to check availability."),
    "leased-lines": ("Business Leased Lines UK: Cost, Speeds and Install",
                     "Business leased lines: dedicated, symmetrical internet with SLA-backed fix times. See cost factors, speeds and install times, then get a quote."),
    "mpls": ("MPLS Networks for Multi-Site Businesses",
             "MPLS networks join your sites on one private network with voice priority. See how MPLS compares with VPN and SD-WAN, then talk to Extera."),
    "sip-trunks": ("SIP Trunks UK: ISDN Replacement and Call Bundles",
                   "SIP trunking in the UK: replace ISDN with phone lines over the internet, keep your numbers and add call bundles. Get a SIP trunk quote."),
    "business-lines": ("Business Phone Lines and ISDN Switch-Off Help",
                       "ISDN and PSTN switch-off explained, plus business phone lines and call packages. Extera audits your lines and plans your move to digital."),
    "backup-connectivity": ("4G and 5G Business Broadband Backup and Failover",
                            "4G and 5G broadband failover keeps phones, card payments and cloud apps running when your main line fails. Get a backup quote."),
    "mobile": ("Business Mobile Contracts: EE, Vodafone and O2",
               "Business mobile contracts, SIM-only plans and data SIMs on EE, Vodafone and O2, managed with your phones. Get a mobile quote from Extera."),
    "data-cabling": ("Structured Data Cabling, Cat6 and Fibre, Banbury",
                     "Structured data cabling in Banbury and across the UK: Cat6, Cat6a and fibre, tested and documented. Book a free site survey with Extera."),
    "support": ("Phone System Support and Maintenance Contracts",
                "Phone system support from Extera: SLA maintenance contracts, ad-hoc help, remote support and urgent fixes. Call 01295 220 600 or send a request."),
    "extera-direct": ("Extera Direct: Business Headsets and Speakerphones",
                      "Buying guide and online shop for business headsets, speakerphones, video conferencing and meeting room equipment from Extera Direct."),
    "about": ("About Extera: Banbury Telecoms Company Since 2001",
              "Extera is a Banbury telecoms company formed in 2001: phone systems, connectivity, mobile and cabling with ISO 9001 and CHAS accreditation."),
    "contact": ("Contact Extera: Business Telecoms in Banbury",
                "Contact Extera in Banbury, Oxfordshire for a quote on business phone systems, broadband, mobile and cabling. Call 01295 220 600 or send an enquiry."),
}

# H2 rewrites per page: old text -> new text. They add the phrases people search for while still reading naturally.
H2_RENAMES = {
    "index": {"Common questions": "Business telecoms FAQs", "Talk to Extera": "Get a quote from Banbury's telecoms specialists"},
    "phone-systems": {"Which one suits you?": "Which business phone system suits you?", "Where to start": "Where to start: cloud, hosted or on-premise"},
    "3cx": {
        "Choose where your phone system lives": "3CX hosted, onsite or in your own cloud",
        "Where the savings come from": "How much does a 3CX phone system cost?",
        "How a 3CX project works": "3CX installation and migration: how a project works",
        "Common questions": "3CX phone system FAQs",
        "Simple, affordable and flexible": "Why choose 3CX: simple, affordable and flexible",
    },
    "3cx-apps": {
        "Enterprise communication on the move": "3CX mobile app: business calls on the move",
        "Use 3CX from any browser or computer": "3CX web client and desktop app for remote and hybrid working",
        "Your office phone, wherever you are": "3CX softphone: your office phone, wherever you are",
        "Common questions": "3CX app FAQs",
    },
    "3cx-video-chat": {
        "Video meetings, included": "3CX video conferencing, included",
        "Talk to website visitors instantly": "3CX live chat: talk to website visitors instantly",
        "WhatsApp, Facebook and SMS, handled properly": "3CX WhatsApp, Facebook Messenger and SMS, handled properly",
        "Common questions": "3CX video and chat FAQs",
    },
    "3cx-integrations": {
        "Know who is calling before you answer": "3CX CRM integration: know who is calling before you answer",
        "Fits in with the tools you already use": "3CX Microsoft 365, Teams and Google Workspace integration",
        "Common questions": "3CX integration FAQs",
    },
    "3cx-ai-analytics": {
        "Clear insight into every call": "3CX reporting and call analytics",
        "AI that does real work": "3CX AI: call summaries, sentiment and transcription",
        "Contact centre tools, built in": "3CX call centre features: queues, wallboard and routing",
        "Common questions": "3CX call centre and AI FAQs",
    },
    "3cx-vs-8x8": {
        "What we would recommend": "Which is better: 3CX or 8x8?",
        "Compare the whole bill, not just the licence": "3CX vs 8x8 total cost: compare the whole bill",
        "Common questions": "3CX vs 8x8 FAQs",
    },
    "8x8": {
        "What is included": "What is included with an 8x8 phone system",
        "Built for flexible, hybrid teams": "Why choose 8x8 as your UK cloud phone system",
        "Common questions": "8x8 FAQs: pricing, numbers and Teams",
    },
    "8x8-voice": {
        "Everything a modern phone system needs": "8x8 calling features: auto attendant, voicemail and recording",
        "Plans for different kinds of user": "8x8 X Series plans for different kinds of user",
        "Common questions": "8x8 phone system FAQs",
    },
    "8x8-meetings": {
        "Video meetings without the setup": "8x8 video conferencing without the setup",
        "Common questions": "8x8 video meetings FAQs",
    },
    "8x8-contact-centre": {
        "A dialler for sales and campaigns": "8x8 predictive dialler for sales and campaigns",
        "Tools that help agents do their best work": "8x8 agent desktop and CRM integration",
        "Common questions": "8x8 contact centre FAQs",
    },
    "8x8-integrations": {
        "Keep Teams, add 8x8 calling": "8x8 Microsoft Teams integration: keep Teams, add 8x8 calling",
        "CRM and helpdesk integrations": "8x8 Salesforce, Dynamics, Zendesk and NetSuite integrations",
        "Common questions": "8x8 integration FAQs",
    },
    "8x8-security": {
        "Recognised standards": "8x8 security certifications: ISO 27001, PCI DSS and Cyber Essentials",
        "What the SLA means in practice": "8x8 uptime SLA and disaster recovery in practice",
        "Common questions": "8x8 security and data residency FAQs",
    },
    "gamma-horizon": {
        "What is included": "What is included with the Gamma Horizon phone system",
        "The phone system essentials, ready to use": "Horizon hosted telephony essentials, ready to use",
        "Common questions": "Gamma Horizon FAQs",
    },
    "gamma-horizon-apps": {"Chat, calls and video in one place": "Horizon Collaborate: chat, calls and video in one place", "Your office phone in your pocket": "Horizon mobile app: your office phone in your pocket", "Common questions": "Horizon app FAQs"},
    "gamma-horizon-teams": {
        "Keep Microsoft Teams, add proper business calling": "Horizon for Teams: keep Microsoft Teams, add direct routing calling",
        "Collaborate, Teams or Webex": "Collaborate, Microsoft Teams phone system or Webex",
        "Common questions": "Horizon Teams and Webex FAQs",
    },
    "gamma-horizon-contact": {"A cloud contact centre alongside your phones": "Horizon Contact: a Gamma contact centre alongside your phones", "Common questions": "Horizon Contact FAQs"},
    "gamma-horizon-analytics": {"See what is happening on every call": "Akixi call analytics: see what is happening on every call", "Common questions": "Horizon analytics FAQs"},
    "gamma-horizon-network": {"Built on a carrier's own network": "The Gamma network: built on a carrier's own network", "Keep taking calls when something breaks": "Call diversion and business continuity when something breaks", "Common questions": "Horizon network and resilience FAQs"},
    "avaya-ip-office": {
        "What is included": "What is included with Avaya IP Office",
        "How an IP Office project works": "Avaya IP Office installation, upgrade and maintenance",
        "Common questions": "Avaya IP Office FAQs",
    },
    "avaya-ipo-editions": {"Choose the right size and type of system": "Avaya IP Office Server Edition, Select and IP500 V2: choose the right system", "Licences or subscription?": "IP Office subscription or licences?", "Common questions": "IP Office edition FAQs"},
    "avaya-ipo-apps": {"Cordless handsets that roam the whole site": "Avaya DECT wireless handsets that roam the whole site", "Your office phone on your computer and mobile": "Avaya Workplace softphone on your computer and mobile", "Common questions": "Avaya Workplace and mobility FAQs"},
    "avaya-ipo-contact-centre": {"Customer service tools that grow with you": "IP Office contact centre tools that grow with you", "Common questions": "IP Office contact centre FAQs"},
    "avaya-ipo-resilience": {
        "The upgrade path to the latest release": "Avaya IP Office R12 upgrade: the path from Release 11",
        "Keep calls going when a link fails": "Survivability and failover: keep calls going when a link fails",
        "Common questions": "IP Office support and upgrade FAQs",
    },
    "contact-centres": {"What a modern contact centre can do": "What modern contact centre software can do", "Common questions": "Contact centre FAQs"},
    "connectivity": {
        "Plan your move away from ISDN now": "ISDN switch-off: plan your move away from ISDN now",
        "The right connection for each site": "How we choose the right connection, backup and managed network",
        "Common questions": "Business connectivity FAQs",
        "Talk to Extera": "Get a business connectivity quote",
    },
    "fibre-broadband": {
        "What you get": "What you get with business fibre broadband",
        "How it works": "How to check availability and order business fibre broadband",
        "Common questions": "Business fibre broadband FAQs",
        "Talk to Extera": "Check your postcode for business broadband",
    },
    "leased-lines": {
        "Why choose a leased line": "Leased line vs broadband: why choose a leased line",
        "Bearer and committed data rate": "Leased line cost: bearer and committed data rate",
        "How it works": "How long does a leased line take to install?",
        "Common questions": "Leased line FAQs",
        "Talk to Extera": "Get a business leased line quote",
    },
    "mpls": {
        "Why MPLS": "MPLS VPN: predictable performance across every site",
        "MPLS, VPN or SD-WAN?": "MPLS vs SD-WAN vs VPN",
        "When MPLS makes sense": "When MPLS makes sense for branch offices",
        "How it works": "How a managed WAN project works",
        "Common questions": "MPLS FAQs",
        "Talk to Extera": "Get an MPLS network quote",
    },
    "sip-trunks": {
        "Why SIP": "SIP trunking UK: lower costs, more flexibility",
        "What to check before you move": "ISDN replacement: what to check before you move",
        "How it works": "How to replace ISDN with SIP trunks",
        "Common questions": "SIP trunk FAQs",
        "Talk to Extera": "Get a SIP trunk quote",
    },
    "business-lines": {
        "Where to move to": "ISDN replacement: where to move to",
        "What we supply": "Business phone lines, ISDN and call packages",
        "Common questions": "ISDN and PSTN switch-off FAQs",
        "Talk to Extera": "Book a free line audit",
    },
    "backup-connectivity": {
        "Why add backup": "4G backup for business continuity",
        "Failover in four moves": "How broadband failover works",
        "4G or 5G backup?": "4G or 5G backup broadband?",
        "How it works": "How to add a leased line backup or 4G failover",
        "Common questions": "Broadband backup FAQs",
        "Talk to Extera": "Get a backup connectivity quote",
    },
    "mobile": {"Common questions": "Business mobile FAQs", "Mobile, matched to how your team works": "Business mobile plans, matched to how your team works", "Talk to Extera": "Get a business mobile quote"},
    "data-cabling": {
        "What we install": "Network cabling, Cat6 and fibre: what we install",
        "A cabling project, step by step": "A structured cabling project, step by step",
        "Common questions": "Data cabling FAQs",
        "Talk to Extera": "Book a free data cabling survey",
    },
    "support": {
        "Choose the level of cover": "Phone system support and maintenance contracts",
        "How a support request works": "Remote support and break-fix: how a request works",
        "Common questions": "Phone system support FAQs",
    },
    "extera-direct": {"Common questions": "Headset and conferencing equipment FAQs"},
}

# One short local sentence added after the first paragraph of the main content.
LOCAL_NOTES = {
    "index": "Extera is a Banbury, Oxfordshire telecoms company supplying business phone systems, business broadband, mobiles and data cabling across Oxfordshire and the whole of the UK.",
    "phone-systems": "Extera is based in Banbury, Oxfordshire, and installs and supports cloud, hosted and on-premise business phone systems for businesses across Oxfordshire and the UK.",
    "3cx": "As a 3CX Gold Partner based in Banbury, Oxfordshire, Extera supplies, installs and supports 3CX phone systems across Oxfordshire and the whole of the UK.",
    "8x8": "Extera, based in Banbury, Oxfordshire, supplies and supports 8x8 cloud phone systems for UK businesses, including numbers, handsets and migration.",
    "gamma-horizon": "Extera, based in Banbury, Oxfordshire, supplies and supports Gamma Horizon hosted telephony for UK businesses, with our own engineers on hand.",
    "avaya-ip-office": "Extera, an Avaya Silver Partner in Banbury, Oxfordshire, supplies, upgrades and maintains Avaya IP Office systems across Oxfordshire and the UK.",
    "connectivity": "Our Banbury, Oxfordshire team compares UK carriers for every site, so you get the right business connectivity, backup and managed network.",
    "fibre-broadband": "Send us your postcode and our Banbury team will check business fibre broadband availability from the UK carriers we use.",
    "leased-lines": "Extera, based in Banbury, Oxfordshire, orders, installs and supports business leased lines for sites across Oxfordshire and the UK.",
    "sip-trunks": "Extera, based in Banbury, Oxfordshire, moves UK businesses from ISDN to SIP trunking, keeping your numbers and planning the cutover with you.",
    "business-lines": "Extera audits business phone lines and plans the ISDN switch-off move for businesses in Banbury, Oxfordshire and across the UK.",
    "mobile": "Extera, based in Banbury, Oxfordshire, supplies business mobile contracts and SIMs on EE, Vodafone and O2 to businesses across the UK.",
    "data-cabling": "Extera's own engineers install structured data cabling in Banbury, Oxfordshire and across mainland UK, including new offices, refits and moves.",
    "support": "Extera supports phone systems from Banbury, Oxfordshire, with our own engineers covering Oxfordshire and the rest of mainland UK.",
    "contact-centres": "Extera, based in Banbury, Oxfordshire, designs, installs and supports contact centre software for UK teams of every size.",
    "contact": "Our office is in Banbury, Oxfordshire, and we cover businesses across Oxfordshire and the rest of the UK.",
}
